package com.follarce.machine.CPU.ALU.RV64IMC;

public class zext6B {
    public static boolean[] module(boolean[] value) {
        boolean[] result = new boolean[64];
        result[0] = value[0];
        result[1] = value[1];
        result[2] = value[2];
        result[3] = value[3];
        result[4] = value[4];
        result[5] = value[5];
        result[6] = false;
        result[7] = false;
        result[8] = false;
        result[9] = false;
        result[10] = false;
        result[11] = false;
        result[12] = false;
        result[13] = false;
        result[14] = false;
        result[15] = false;
        result[16] = false;
        result[17] = false;
        result[18] = false;
        result[19] = false;
        result[20] = false;
        result[21] = false;
        result[22] = false;
        result[23] = false;
        result[24] = false;
        result[25] = false;
        result[26] = false;
        result[27] = false;
        result[28] = false;
        result[29] = false;
        result[30] = false;
        result[31] = false;
        result[32] = false;
        result[33] = false;
        result[34] = false;
        result[35] = false;
        result[36] = false;
        result[37] = false;
        result[38] = false;
        result[39] = false;
        result[40] = false;
        result[41] = false;
        result[42] = false;
        result[43] = false;
        result[44] = false;
        result[45] = false;
        result[46] = false;
        result[47] = false;
        result[48] = false;
        result[49] = false;
        result[50] = false;
        result[51] = false;
        result[52] = false;
        result[53] = false;
        result[54] = false;
        result[55] = false;
        result[56] = false;
        result[57] = false;
        result[58] = false;
        result[59] = false;
        result[60] = false;
        result[61] = false;
        result[62] = false;
        result[63] = false;
        return result;
    }
}
